#!/bin/bash
i=0;
while IFS='' read -r line || [[ -n "$line" ]]; do
	echo $line > line;
	if [[ "`diff -w line end`" = "" ]]
	then
		i=$(($i + 1));
		echo "" > ../$i.php
	else
		echo "$line" >> ../$i.php
	fi
done < all.php
