<html lang="en"><head><meta charset="utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/><meta name="description" content="The core aim of our project is to create online learning management system that combines best practices in organizing training so that it will be interesting, useful and much easier for the students. The most important part of our project is to fertilize future programmers, showing them that it is not as difficult as it sounds. This will happen through brief and extensive online practical competitions taken their levels, with certificates and prizes for the best ones."/><meta name="author" content="Tech Education ++"/><meta name="keywords" content="Learning, Online, System, Presentations, Videos, Exam"/><meta name="distribution" content="web"/><meta name="robots" content="index, follow"/><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/><link rel="icon" href="/favicon.png"/><title>Student System</title><!--link(href='/css/jumbotron.css', rel='stylesheet')--><link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700"/><link rel="stylesheet" href="//fonts.googleapis.com/icon?family=Material+Icons"/><link rel="stylesheet" href="/css/bootstrap.min.css"/><link rel="stylesheet" href="/css/bootstrap-material-design.min.css"/><link rel="stylesheet" href="/css/ripples.min.css"/><link rel="stylesheet" href="/css/snackbar.min.css"/><link rel="stylesheet" href="/css/extension.css"/><style type="text/css"></style><style type="text/css">.container {
	background-color: white;
	border: 15px solid white;
}
h3 {
	color: black !important;
}
</style></head><body><nav class="navbar navbar-default"><!--default--><div class="container-fluid"><div class="navbar-header"><a href="/" class="navbar-brand">TechEdu ++</a><ul class="nav navbar-nav"><li><a href="/">Home</a></li><li><a href="/news">News</a></li><li><a href="https://chat.techedu.cf">Chat</a></li><li class="active"><a href="#">About</a></li></ul></div></div></nav><div class="container"><div class="row"><h1>Authors:</h1><div style="height: 450px;" class="col-md-4"><a href="https://techedu.cf/members/alex" class="normal"><img height="150px" src="/img/main.jpg"/><h2>Alex Tsvetanov</h2></a><br/><h3>Team leader</h3><p>Developer, Contestant in Informatics</p><p>Designer</p><p>DataBases and Server Support</p><h3>Trainer</h3></div><div style="height: 450px;" class="col-md-4"><a href="https://techedu.cf/members/dimo" class="normal"><img height="150px" src="/aboutus/aboutus/dimo.jpg"/><h2>Dimo Chanev</h2></a><br/><h3>Technical Support</h3><p>Developer, Contestant in Informatics</p><h3>Admin of <strong>"The Judgata"</strong></h3></div></div><div class="row"><h1>Lectors:</h1><!--.col-md-4(style='height: 450px;')
	a.normal(href='https://techedu.cf/members/radoslav_iliev')
		img(style="height: 150px", src='/members/img/radoslav_iliev.png')
		h2 Radoslav Iliev
	h3 Trainer
	ul
		li
			h4 Embedded systems
		li
			h4 Internet of things
		li
			h4 C, Java, Basic
	p
		| The Professional School of Computer Technologies, Pravets, 11
		sup -th
		|  grade.--><div style="height: 450px;" class="col-md-4"><a href="https://techedu.cf/members/iasen_georgiev" class="normal"><img style="height: 150px" src="/members/img/iasen_georgiev.jpg"/><h2>Yasen Georgiev</h2></a><h3>Trainer</h3><ul><li><h4>PHP</h4></li><li><h4>MySQL</h4></li></ul></div><div style="height: 450px;" class="col-md-4"><a href="https://techedu.cf/members/marin_shalamanov" class="normal"><img style="height: 150px" src="/members/img/marin_shalamanov.jpg"/><h2>Marin Shalamanov</h2></a><h3>Trainer</h3><ul><li><h4>Student at the Faculty of Mathematics and Informatics at Sofia University</h4></li><li><h4>Trainer at SAP Labs Bulgaria</h4></li><li><h4>Trainer in PCHMG</h4></li></ul></div><div style="height: 450px;" class="col-md-4"><a href="https://techedu.cf/members/evlogi_hristov" class="normal"><img style="height: 150px" src="/members/img/evlogi_hristov.jpg"/><h2>Evlogi Hristov</h2></a><h3>Trainer</h3><ul><li><h4>Algorithms</h4></li><li><h4>HTML, CSS &amp; JavaScript</h4></li><li><h4>C#</h4></li></ul><p></p></div><div style="height: 450px;" class="col-md-4"><!--a.normal(href='')--><img style="height: 150px" src="/members/img/no_profile.png"/><h2>Evgeni Vasilev</h2><h3>Trainer</h3><ul><li><h4>Algorithms</h4></li><li><h4>HTML, CSS &amp; JavaScript</h4></li><li><h4>C/C++</h4></li></ul><p><National>Gymnasium of Natural Sciences and Mathematics</National></p></div></div></div><footer><center><p>Copyrights © Tech Education++ 2016-2017</p></center></footer><script src="/js/jquery.min.js"></script><script src="/js/tether.min.js"></script><script src="/js/bootstrap.min.js"></script><script src="/js/material.min.js"></script><script src="/js/ripples.min.js"></script><script src="/js/snackbar.min.js"></script><script src="/js/jquery.nouislider.min.js"></script><script src="/js/main.js"></script></body></html>