<html lang="en"><head><meta charset="utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/><meta name="description" content="The core aim of our project is to create online learning management system that combines best practices in organizing training so that it will be interesting, useful and much easier for the students. The most important part of our project is to fertilize future programmers, showing them that it is not as difficult as it sounds. This will happen through brief and extensive online practical competitions taken their levels, with certificates and prizes for the best ones."/><meta name="author" content="Tech Education ++"/><meta name="keywords" content="Learning, Online, System, Presentations, Videos, Exam"/><meta name="distribution" content="web"/><meta name="robots" content="index, nofollow"/><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/><link rel="icon" href="/favicon.png"/><title>Student System</title><link href="/css/jumbotron.css" rel="stylesheet"/><link rel="stylesheet" href="/bootstrap/dist/css/bootstrap.min.css"/><link rel="stylesheet" href="/css/extension.css"/><script src="/js/jquery.min.js"></script><script src="/bootstrap/dist/js/bootstrap.min.js"></script><style type="text/css">footer {
	color: white;
}
</style><style type="text/css">body {
	/*background-color: #00AD00;*/
	background-image: url("/128-61.jpg");
}
footer {
	color: white;
}

</style></head><body style="background-image: url('/128-61.jpg');"><nav class="navbar navbar-inverse"><!--default--><div class="container-fluid"><div class="navbar-header"><a href="/" class="navbar-brand">TechEdu ++</a><ul class="nav navbar-nav"><li class="active"><a href="/">Home</a></li><li><a href="/news">News</a></li><li><a href="https://chat.techedu.cf">Chat</a></li><li><a href="/aboutus.php">About</a></li></ul></div></div></nav><div class="jumbotron"><div class="container"><h1 class="display-3">{{title}}</h1><p>This academy can teach you how to be good at computer sciences</p></div></div><div class="container"><div class="row">{{all}}</div></div><hr/><footer><center><p>Copyrights © Tech Education++ 2016-2017</p></center></footer></body></html>